---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  selector:
    matchLabels: 
      app: user-microservice
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: user-microservice
        tier: backend
        track: stable
    spec:
      containers:
        - name: user-microservice
          image: coecomber/microservicesg3:userpoging3
          ports:
            - name: http
              containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 8099
      #Port to forward to inside the pod
      targetPort: 8090
      #Port accessible outside cluster
      nodePort: 30103
  type: LoadBalancer