language: java

jobs:
  include:
    - stage: User-service
      script: 
        - cd User-Service/
        - mvn verify
        - mvn clean test

    - stage: Friend-service
      script: 
        - cd Friend-Service/
        - mvn verify
        - mvn clean test

    - stage: Friendchat-service
      script: 
        - cd FriendChat-Service/
        - mvn verify
        - mvn clean test

    - stage: Lobby-service
      script: 
        - cd Lobby-Service/
        - mvn verify
        - mvn clean test

    - stage: Lobbychat-service
      script: 
        - cd LobbyChat-Service/
        - mvn verify
        - mvn clean test

    - stage: LobbychatWebsocket
      script: 
        - cd LobbyChatWebsocket/
        - mvn verify
        - mvn clean test     

    - stage: Lobbywebsocket
        script: 
          - cd LobbyWebsocket/
          - mvn verify
          - mvn clean test 



after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success https://discordapp.com/api/webhooks/664069203757629460/DZTfqwtS_aqRiqAwE46em_LplfjZpsvEGqv-Wuy4Oc_WfZ4b2-kPUWCEvp4GxQynxK7R
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discordapp.com/api/webhooks/664069203757629460/DZTfqwtS_aqRiqAwE46em_LplfjZpsvEGqv-Wuy4Oc_WfZ4b2-kPUWCEvp4GxQynxK7R